<%@ page language="java" contentType="text/html; charset=UTF-8" %>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>正在跳转</title>
</head>
<body>
<%
    // Generated by Payment service, this html content contains a prepared form
    // and a js code to submit it automatically to the 3rd party payment gateway.
    out.println(request.getAttribute("html"));
%>
</body>
</html>